# Generated by Django 5.0 on 2023-12-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women_app', '0002_woman_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woman',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='woman',
            index=models.Index(fields=['slug'], name='women_app_w_slug_629e2c_idx'),
        ),
        migrations.AddConstraint(
            model_name='woman',
            constraint=models.UniqueConstraint(fields=('slug',), name='slug_unique_constraint'),
        ),
    ]
