# Generated by Django 5.0 on 2023-12-28 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women_app', '0002_woman_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='woman',
            options={'verbose_name': 'woman', 'verbose_name_plural': 'women'},
        ),
    ]
