# Generated by Django 5.0 on 2023-12-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women_app', '0003_alter_woman_slug_woman_women_app_w_slug_629e2c_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WomanCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=255)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='woman',
            name='slug_unique_constraint',
        ),
        migrations.AddConstraint(
            model_name='woman',
            constraint=models.UniqueConstraint(fields=('slug',), name='cat_slug_unique_constraint'),
        ),
        migrations.AddIndex(
            model_name='womancategory',
            index=models.Index(fields=['slug'], name='women_app_w_slug_6a0a22_idx'),
        ),
        migrations.AddConstraint(
            model_name='womancategory',
            constraint=models.UniqueConstraint(fields=('slug',), name='slug_unique_constraint'),
        ),
    ]
