# Generated by Django 5.0 on 2023-12-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women_app', '0004_womancategory_remove_woman_slug_unique_constraint_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='woman',
            name='cat_slug_unique_constraint',
        ),
        migrations.RemoveConstraint(
            model_name='womancategory',
            name='slug_unique_constraint',
        ),
        migrations.AddConstraint(
            model_name='woman',
            constraint=models.UniqueConstraint(fields=('slug',), name='woman_slug_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='womancategory',
            constraint=models.UniqueConstraint(fields=('slug',), name='cat_slug_unique_constraint'),
        ),
    ]
