# Generated by Django 5.0 on 2023-12-29 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women_app', '0005_remove_woman_cat_slug_unique_constraint_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='woman',
            name='women_app_w_slug_629e2c_idx',
        ),
        migrations.RemoveIndex(
            model_name='womancategory',
            name='women_app_w_slug_6a0a22_idx',
        ),
    ]
