# Generated by Django 5.0 on 2023-12-29 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women_app', '0007_woman_women_app_w_slug_629e2c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='woman',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='women_app.womancategory'),
        ),
    ]
