# Generated by Django 5.0 on 2023-12-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women_app', '0013_posttag_posttag_tag_slug_unique_constraint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woman',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='women_app.posttag'),
        ),
    ]
