# Generated by Django 5.0 on 2023-12-29 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women_app', '0017_alter_woman_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Man',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddIndex(
            model_name='posttag',
            index=models.Index(fields=['slug'], name='women_app_p_slug_30e053_idx'),
        ),
        migrations.AddField(
            model_name='woman',
            name='husband',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wife', to='women_app.man'),
        ),
    ]
