# Generated by Django 5.0 on 2024-01-04 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women_app', '0018_man_posttag_women_app_p_slug_30e053_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='woman',
            options={'default_manager_name': 'published', 'ordering': ['time_created'], 'verbose_name': 'Woman', 'verbose_name_plural': 'Women'},
        ),
    ]
