# Generated by Django 5.0 on 2024-01-04 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women_app', '0019_alter_woman_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='woman',
            options={'default_manager_name': 'published', 'get_latest_by': 'time_created', 'ordering': ['time_created'], 'verbose_name': 'Woman', 'verbose_name_plural': 'Women'},
        ),
    ]
