# Generated by Django 5.0 on 2024-01-04 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women_app', '0022_man_marriages_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woman',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', related_query_name='post', to='women_app.womancategory'),
        ),
        migrations.AlterField(
            model_name='woman',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', related_query_name='post', to='women_app.posttag'),
        ),
    ]
