# Generated by Django 5.0 on 2024-01-04 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women_app', '0023_alter_woman_category_alter_woman_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='woman',
            options={'base_manager_name': 'published', 'default_manager_name': 'published', 'get_latest_by': 'time_created', 'verbose_name': 'Woman', 'verbose_name_plural': 'Women'},
        ),
    ]
