# Generated by Django 5.0 on 2024-01-09 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women_app', '0032_alter_woman_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='woman',
            options={'get_latest_by': 'time_created', 'verbose_name': 'Жінка', 'verbose_name_plural': 'Жінки'},
        ),
        migrations.AlterModelOptions(
            name='womancategory',
            options={'verbose_name': 'Категорія публікації', 'verbose_name_plural': 'Категорії публікацій'},
        ),
        migrations.AlterModelManagers(
            name='woman',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='woman',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', related_query_name='post', to='women_app.womancategory', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='woman',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст статті'),
        ),
        migrations.AlterField(
            model_name='woman',
            name='status',
            field=models.IntegerField(choices=[(0, 'Чернетка'), (1, 'Опубліковано')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='woman',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Час створення'),
        ),
        migrations.AlterField(
            model_name='woman',
            name='time_last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Час останньої зміни'),
        ),
        migrations.AlterField(
            model_name='woman',
            name='title',
            field=models.CharField(max_length=255, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='womancategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва категорії'),
        ),
    ]
