# Generated by Django 5.0 on 2024-01-10 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women_app', '0036_alter_woman_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='woman',
            options={'get_latest_by': 'time_created', 'ordering': ('-time_last_modified',), 'verbose_name': 'Жінка', 'verbose_name_plural': 'Жінки'},
        ),
    ]
