# Generated by Django 5.0 on 2024-01-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women_app', '0037_alter_woman_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFilesForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_model', verbose_name='Файл для завантаження')),
            ],
        ),
        migrations.AlterField(
            model_name='woman',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', related_query_name='post', to='women_app.posttag', verbose_name='Теги'),
        ),
    ]
