# Generated by Django 5.0 on 2024-01-16 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women_app', '0038_uploadfilesform_alter_woman_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadFilesForm',
            new_name='UploadFilesModel',
        ),
    ]
