# Generated by Django 5.0 on 2024-01-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women_app', '0039_rename_uploadfilesform_uploadfilesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='woman',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
