# Generated by Django 5.0 on 2024-01-18 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women_app', '0040_woman_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woman',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', related_query_name='post', to='women_app.womancategory', verbose_name='Категорія'),
        ),
    ]
